# Keycloak configuration
quarkus.oidc-client.auth-server-url=http://34.142.154.181/auth/realms/master
quarkus.oidc-client.client-id=minh-client-service
quarkus.oidc-client.credentials.secret=minh-client-service
quarkus.oidc-client.grant.type=client_credentials

# Resource service URL
org.acme.ResourceServiceClient/mp-rest/url=http://localhost:8080
