# Keycloak configuration
# quarkus.oidc-client.auth-server-url=http://34.142.154.181/auth/realms/master
# quarkus.oidc-client.client-id=minh-client-service
# quarkus.oidc-client.credentials.secret=mgsOvXewbmJgJiLUmC3w33QDFEbVrjI5
# quarkus.oidc-client.grant.type=client
quarkus.oidc.auth-server-url=http://34.142.154.181/realms/master
quarkus.oidc.client-id=minh-client-service
quarkus.oidc.credentials.secret=mgsOvXewbmJgJiLUmC3w33QDFEbVrjI5
quarkus.oidc.grant.type=client
quarkus.oidc.enabled=true
quarkus.oidc.tls.verification=none

# Resource service URL
org.acme.ResourceServiceClient/mp-rest/url=https://resource-service-826941272251.asia-southeast1.run.app
