# Keycloak configuration
quarkus.oidc-client.auth-server-url=https://your-keycloak-server/auth/realms/your-realm
quarkus.oidc-client.client-id=client-service
quarkus.oidc-client.credentials.secret=your-client-secret
quarkus.oidc-client.grant-type=client_credentials

# Resource service URL
org.acme.ResourceServiceClient/mp-rest/url=http://localhost:8080
